server:
  port: 8080
logging:
  level:
    root: info
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/grandmaster
    username: gm_client
    password: grandmaster
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    hibernate:      ddl-auto: create
    properties:      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/grandmaster
    user: gm_client
    password: grandmaster
    schemas:
    - "grandmaster"
    